name: Prod Node App

on:
  push:
    branches:
      - master 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      id: heroku
      uses: jctaveras/heroku-deploy@v1.0.0
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: ${{ secrets.HEROKU_APP_NAME_PROD }}
        dockerfile: '.'

  curl:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://my-hello-node-prod.herokuapp.com/
